name = "MLJTestIntegration"
uuid = "697918b4-fdc1-4f9e-8ff9-929724cee270"
authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
version = "0.1.0"

[deps]
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
MLJ = "0.18"
julia = "1.6"
